drop table if exists teaeduc.PROFESSOR
create TABLE teaeduc.PROFESSOR (
	ID_PROFESSOR INT NOT NULL AUTO_INCREMENT,
	ID_INSTITUICAO INT not null,
	CPF VARCHAR(255) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	EMAIL  VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(255) NULL,
	primary key (ID_PROFESSOR),
	CONSTRAINT fkInstituicaoProfessor FOREIGN KEY (ID_INSTITUICAO) REFERENCES instituicao(ID_INSTITUICAO)
);

alter table teaeduc.PROFESSOR
add unique (EMAIL);