CREATE TABLE teaeduc.INSTITUICAO (
	ID_INSTITUICAO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL,
	CNPJ VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	CEP INT NOT NULL,
	ENDERECO VARCHAR (4000)NOT NULL,
	NUMERO INT NOT NULL,
	BAIRRO VARCHAR(2000) NOT NULL,
	CIDADE VARCHAR (2000) NOT NULL,
	UF VARCHAR(255) NOT NULL,
	TELEFONE INT NOT null,
	primary key (ID_INSTITUICAO)
);

alter table teaeduc.INSTITUICAO
add unique (CNPJ);