CREATE TABLE teaeduc.ATIVIDADE (
	ID_ATIVIDADE INT NOT NULL AUTO_INCREMENT,
	ID_PROFESSOR INT NOT NULL,
    TIPO_ATIVIDADE VARCHAR(255) NOT NULL,
	NOME_ATIVIDADE VARCHAR(255) NOT NULL,
    QTD_ATIVIDADE INT NOT NULL,
	primary key (ID_ATIVIDADE),
	CONSTRAINT fkProfessorAtividade FOREIGN KEY (ID_PROFESSOR) REFERENCES professor(ID_PROFESSOR)
);


CREATE TABLE teaeduc.EXERCICIO_LTR_SLB (
	ID_EXERCICIO INT NOT NULL AUTO_INCREMENT,
	ID_ATIVIDADE INT NOT NULL,
    TIPO_EXERCICIO VARCHAR(255) NOT NULL,
    PALAVRA_BASE VARCHAR(255) NOT NULL,
	primary key (ID_EXERCICIO),
	CONSTRAINT fkAtividadeExercicio FOREIGN KEY (ID_ATIVIDADE) REFERENCES atividade(ID_ATIVIDADE)
);

CREATE TABLE teaeduc.EXERCICIO_IMG (
	ID_EXERCICIO_IMG INT NOT NULL AUTO_INCREMENT,
	ID_EXERCICIO INT NOT NULL,
    PATH_IMAGEM VARCHAR(2000) NOT NULL,
    PATH_PARABENIZACAO VARCHAR(2000) NOT NULL,
	primary key (ID_EXERCICIO_IMG),
	CONSTRAINT fkExercicioImagem FOREIGN KEY (ID_EXERCICIO) REFERENCES exercicio_ltr_slb(ID_EXERCICIO)
);

CREATE TABLE teaeduc.EXERCICIO_IMAGEM (
	ID_EXERCICIO_IMAGEM INT NOT NULL AUTO_INCREMENT,
	ID_ATIVIDADE INT NOT NULL,
    TIPO_EXERCICIO VARCHAR(255) NOT NULL,
    PALAVRA_BASE_1 VARCHAR(255) NOT NULL,
    PALAVRA_BASE_2 VARCHAR(255),
    PALAVRA_BASE_3 VARCHAR(255),
    PALAVRA_BASE_4 VARCHAR(255),
    PATH_IMAGEM_1 VARCHAR(500) NOT NULL,
    PATH_IMAGEM_2 VARCHAR(500),
    PATH_PARABENIZACAO VARCHAR(500),
	primary key (ID_EXERCICIO_IMAGEM),
	CONSTRAINT fkAtividadeExercicioImagem FOREIGN KEY (ID_ATIVIDADE) REFERENCES atividade(ID_ATIVIDADE)
);


CREATE TABLE teaeduc.ATIVIDADE_ALUNO (
	ID_ATIVIDADE_ALUNO INT NOT NULL AUTO_INCREMENT,
	ID_ATIVIDADE INT NOT NULL,
    ID_ALUNO INT NOT NULL,
    CONCLUIDO INT,
	primary key (ID_ATIVIDADE_ALUNO),
	CONSTRAINT fkAtividadeAtiviadadeAluno FOREIGN KEY (ID_ATIVIDADE) REFERENCES atividade(ID_ATIVIDADE),
    CONSTRAINT fkAlunoAtividadeAluno FOREIGN KEY (ID_ALUNO) REFERENCES aluno(ID_ALUNO)
);

CREATE TABLE teaeduc.RELATORIO_ALUNO (
	ID_RELATORIO_ALUNO INT NOT NULL AUTO_INCREMENT,
	ID_ATIVIDADE INT NOT NULL,
    ID_ALUNO INT NOT NULL,
    TEMPO VARCHAR(255),
	primary key (ID_RELATORIO_ALUNO),
	CONSTRAINT fkAtividadeRelatorioAluno FOREIGN KEY (ID_ATIVIDADE) REFERENCES atividade(ID_ATIVIDADE),
    CONSTRAINT fkAlunoRelatorioAluno FOREIGN KEY (ID_ALUNO) REFERENCES aluno(ID_ALUNO)
);