CREATE TABLE teaeduc.PROFESSOR_INSTITUICAO  (
	ID_PROFESSOR_INSTITUICAO INT NOT NULL AUTO_INCREMENT,
	ID_PROFESSOR INT NOT null,
	ID_INSTITUICAO INT not null,
	STATUS INT(1) not null,
	primary key (ID_PROFESSOR_INSTITUICAO),
	CONSTRAINT fkProfessor FOREIGN KEY (ID_PROFESSOR) REFERENCES professor(ID_PROFESSOR),
	CONSTRAINT fkInstituicao FOREIGN KEY (ID_INSTITUICAO) REFERENCES instituicao(ID_INSTITUICAO)
);